### ISSUE TITLE
set_loadout_palette does not accept the value of 6. Causes error when Encoding invasion xml.

### ISSUE THREAD

**Issue by Person123422** [KornnerStudios/KSoft.Blam#1]
Tried to make modifications to an invasion gametype. When I tried to encode it I got an error saying "A LoadoutPalette reference has an invalid value 6". I have attached the error to this issue.
[loadout_error.txt](https://github.com/KornnerStudios/KSoft.Blam/files/3985765/loadout_error.txt)

**Comment by Person123422** [comment]
I think this is because the value of 0 is getting confused with the first loadout palette. It is not the first loadout palette and is actually none. The invasion gametype uses the value of 0 to disable loadouts after the 3rd section is complete. Line 1998 of an ordinary invasion gametype XML uses the value of 0 to disable loadouts.

**Comment by kornman00** [comment]
Thanks, I'll try to take a look at this between this weekend and next and figure out what's wrong

**Comment by kornman00** [comment]
@Person123422 I've resolved this. I'm hoping to put out a new build tomorrow after seeing if I can make some other tweaks. Cheers!
